version: '3.7'

services:
  regression:
    image: python:3.11.8-slim
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "ls -la && pytest -sv --alluredir=allure-results"
    working_dir: /usr/workspace
